[mypy]
python_version = 3.12
strict = True
mypy_path = src
files = src

[mypy-cvxpy]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-psycopg]
ignore_missing_imports = True

[mypy-psycopg.rows]
ignore_missing_imports = True
