from __future__ import annotations

from src.api.routers.wave_campaign_approval_decision_http import (
    list_campaign_definition_approval_decisions_response as list_campaign_definition_approval_decisions_response,
    record_campaign_definition_approval_decision_response as record_campaign_definition_approval_decision_response,
)
from src.api.routers.wave_campaign_assignment_action_http import (
    list_campaign_definition_assignment_actions_response as list_campaign_definition_assignment_actions_response,
    record_campaign_definition_assignment_action_response as record_campaign_definition_assignment_action_response,
)
from src.api.routers.wave_campaign_assignment_task_http import (
    list_campaign_definition_assignment_tasks_response as list_campaign_definition_assignment_tasks_response,
    open_campaign_definition_assignment_task_response as open_campaign_definition_assignment_task_response,
    transition_campaign_definition_assignment_task_response as transition_campaign_definition_assignment_task_response,
)
from src.api.routers.wave_campaign_maker_checker_http import (
    list_campaign_definition_maker_checker_controls_response as list_campaign_definition_maker_checker_controls_response,
    record_campaign_definition_maker_checker_control_response as record_campaign_definition_maker_checker_control_response,
)
