"""Shared operating-boundary declarations for campaign read models."""

CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION = "NO_MAKER_CHECKER_CONTROL_STATE_MUTATION"

CAMPAIGN_APPROVAL_INBOX_OPERATING_BOUNDARIES = [
    "READ_ONLY_APPROVAL_ATTENTION",
    "NO_APPROVAL_STATE_MUTATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_ASSIGNMENT_PLAN_OPERATING_BOUNDARIES = [
    "READ_ONLY_ASSIGNMENT_PLAN",
    "NO_ASSIGNMENT_STATE_MUTATION",
    "NO_ESCALATION_TASK_CREATION",
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_SOURCE_FACT_RECALCULATION",
    "NO_APPROVAL_STATE_MUTATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_OPERATING_QUEUE_BOUNDARIES = [
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_SOURCE_FACT_RECALCULATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_WORKFLOW_BOARD_OPERATING_BOUNDARIES = [
    "READ_ONLY_WORKFLOW_BOARD",
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_SOURCE_FACT_RECALCULATION",
    "NO_APPROVAL_STATE_MUTATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_WORKFLOW_OVERVIEW_OPERATING_BOUNDARIES = [
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_SOURCE_FACT_RECALCULATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_LAUNCH_PACKAGE_OPERATING_BOUNDARIES = [
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_MEMBERSHIP_RECALCULATION",
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_LAUNCH_HISTORY_OPERATING_BOUNDARIES = [
    CAMPAIGN_NO_MAKER_CHECKER_CONTROL_STATE_MUTATION,
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]

CAMPAIGN_WORKFLOW_AUTOMATION_OPERATING_BOUNDARIES = [
    "READ_ONLY_WORKFLOW_AUTOMATION_PLAN",
    "NO_AUTOMATIC_TASK_MUTATION",
    "NO_EXTERNAL_WORKFLOW_ORCHESTRATION",
    "NO_GLOBAL_PORTFOLIO_UNIVERSE_DISCOVERY",
    "NO_SOURCE_FACT_RECALCULATION",
    "NO_APPROVAL_STATE_MUTATION",
    "NO_AUTOMATIC_MAKER_CHECKER_MUTATION",
    "NO_CLIENT_CONTACT",
    "NO_TRADE_APPROVAL",
    "NO_ORDER_GENERATION",
    "NO_OMS_EXECUTION_CLAIM",
]
