"""RFC-0042 post-trade outcome domain primitives."""

from src.core.outcomes.comparison import (
    compare_outcome_dimension,
    compare_outcome_dimensions,
)
from src.core.outcomes.core_sources import (
    CoreOutcomeSourceError,
    realized_cash_source_from_cash_balances_response,
    unavailable_core_cash_source,
)
from src.core.outcomes.models import (
    DpmExpectedOutcomeSnapshot,
    DpmOutcomeDimensionInput,
    DpmOutcomeDimensionResult,
    DpmOutcomeEvent,
    DpmOutcomeMetricValue,
    DpmOutcomeReviewWindow,
    DpmOutcomeReviewComparison,
    DpmOutcomeSourceFreshness,
    DpmOutcomeSourceRef,
    DpmOutcomeSupportability,
    DpmOutcomeTolerance,
    DpmOutcomeRetentionMetadata,
    DpmPostTradeOutcomeReview,
    DpmRealizedOutcomeSnapshot,
    DpmRealizedSourceSnapshot,
    OutcomeComparisonDirection,
    OutcomeDimension,
    OutcomeDimensionState,
    OutcomeEventType,
    OutcomeReviewState,
)
from src.core.outcomes.snapshots import (
    DpmExpectedSnapshotAssemblyError,
    assemble_expected_outcome_snapshot,
)
from src.core.outcomes.realized_sources import assemble_realized_outcome_snapshot
from src.core.outcomes.performance_sources import (
    PerformanceOutcomeSourceError,
    realized_active_performance_source_from_workspace_summary,
    realized_mwr_source_from_workspace_summary,
    realized_performance_source_from_workspace_summary,
    unavailable_performance_source,
)
from src.core.outcomes.risk_sources import (
    RiskOutcomeSourceError,
    realized_concentration_source_from_concentration_response,
    realized_drawdown_source_from_drawdown_response,
    realized_risk_source_from_risk_metrics_report,
    unavailable_risk_source,
)
from src.core.outcomes.handoffs import (
    OUTCOME_AI_EVIDENCE_REF_TYPE,
    OUTCOME_REPORT_INPUT_REF_TYPE,
    DpmOutcomeAiEvidenceInput,
    DpmOutcomeAiDimensionEvidence,
    DpmOutcomeReportDimension,
    DpmOutcomeReportInput,
    assert_no_ai_forbidden_fields,
    build_ai_evidence_input,
    build_report_input,
)

__all__ = [
    "DpmExpectedOutcomeSnapshot",
    "DpmExpectedSnapshotAssemblyError",
    "DpmOutcomeAiDimensionEvidence",
    "DpmOutcomeAiEvidenceInput",
    "DpmOutcomeDimensionInput",
    "DpmOutcomeDimensionResult",
    "DpmOutcomeEvent",
    "DpmOutcomeMetricValue",
    "DpmOutcomeReviewWindow",
    "DpmOutcomeReviewComparison",
    "DpmOutcomeReportDimension",
    "DpmOutcomeReportInput",
    "DpmOutcomeRetentionMetadata",
    "DpmOutcomeSourceFreshness",
    "DpmOutcomeSourceRef",
    "DpmOutcomeSupportability",
    "DpmOutcomeTolerance",
    "DpmPostTradeOutcomeReview",
    "DpmRealizedOutcomeSnapshot",
    "DpmRealizedSourceSnapshot",
    "CoreOutcomeSourceError",
    "OutcomeComparisonDirection",
    "OutcomeDimension",
    "OutcomeDimensionState",
    "OutcomeEventType",
    "OutcomeReviewState",
    "OUTCOME_AI_EVIDENCE_REF_TYPE",
    "OUTCOME_REPORT_INPUT_REF_TYPE",
    "PerformanceOutcomeSourceError",
    "RiskOutcomeSourceError",
    "assemble_expected_outcome_snapshot",
    "assemble_realized_outcome_snapshot",
    "assert_no_ai_forbidden_fields",
    "build_ai_evidence_input",
    "build_report_input",
    "compare_outcome_dimension",
    "compare_outcome_dimensions",
    "realized_cash_source_from_cash_balances_response",
    "realized_active_performance_source_from_workspace_summary",
    "realized_concentration_source_from_concentration_response",
    "realized_drawdown_source_from_drawdown_response",
    "realized_mwr_source_from_workspace_summary",
    "realized_performance_source_from_workspace_summary",
    "realized_risk_source_from_risk_metrics_report",
    "unavailable_core_cash_source",
    "unavailable_performance_source",
    "unavailable_risk_source",
]
